  deploy:
   runs-on: ubuntu-latest
   needs: build

  steps:
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu
          ./deploy.shdeploy:
  
